# Generated by Django 6.0.3 on 2026-03-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id_rifa', models.AutoField(primary_key=True, serialize=False)),
                ('Nom_rifa', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
