# Generated by Django 6.0.3 on 2026-03-04 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='cant_tickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rifa',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
