# Generated by Django 6.0.3 on 2026-03-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0002_rifa_cant_tickets_rifa_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='cant_tickets',
            field=models.IntegerField(),
        ),
    ]
