# Generated by Django 6.0.3 on 2026-03-09 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0003_alter_rifa_cant_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id_comprador', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Apellidos_com', models.CharField(max_length=50)),
                ('cedula', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Apellidos_vend', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='rifa',
            old_name='estado',
            new_name='estado_rifa',
        ),
        migrations.AddField(
            model_name='rifa',
            name='fecha_Sorteo',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='lote_rige',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='precio_ticket',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='premio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_Ticket', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('comprado', models.BooleanField()),
                ('precio_ticket', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_Pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deuda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_Comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rifas.comprador')),
                ('id_Rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Rifas.rifa')),
                ('id_Vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rifas.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_Trans', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_Abono', models.CharField(max_length=50)),
                ('fecha_transaccion', models.DateField(auto_now_add=True)),
                ('metodo_Pago', models.CharField(max_length=50)),
                ('id_Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_ticket', to='Rifas.ticket')),
                ('id_Vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_vendedor', to='Rifas.vendedor')),
            ],
        ),
    ]
