# Generated by Django 6.0.3 on 2026-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0004_comprador_vendedor_rename_estado_rifa_estado_rifa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='fecha_Sorteo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='lote_rige',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='precio_ticket',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='premio',
            field=models.CharField(max_length=100),
        ),
    ]
