# Generated by Django 6.0.3 on 2026-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0005_alter_rifa_fecha_sorteo_alter_rifa_lote_rige_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
