# Generated by Django 6.0.3 on 2026-03-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0006_alter_ticket_comprado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deuda',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_Pagado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
