# Generated by Django 6.0.3 on 2026-03-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0007_alter_ticket_deuda_alter_ticket_total_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='id_Comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_comprador', to='Rifas.comprador'),
        ),
    ]
