# Generated by Django 6.0.3 on 2026-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rifas', '0008_transaccion_id_comprador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='abonado',
            field=models.BooleanField(default=False),
        ),
    ]
